# Generated by Django 5.0.7 on 2024-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisaStream', '0002_gender_nationality_alter_application_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
